name: Continous Deployment

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: skaha
      -
        name: Checkout
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v2
      -
        name: Set up Python
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      -
        name: Install dependencies
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
      -
        name: Build and publish
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
