name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: pip install --upgrade "poetry>=1.2.2"
      - run: poetry install --without=dev -E docs
      - run: mkdocs gh-deploy --force
